version: '3'

services:
    sciencebeam-judge:
        build:
            context: .
            dockerfile: Dockerfile
        image: elifesciences/sciencebeam-judge:${IMAGE_TAG}
    sciencebeam-judge-jupyter:
        build:
            context: .
            dockerfile: Dockerfile.jupyter
        image: elifesciences/sciencebeam-judge-jupyter:${IMAGE_TAG}
        command: start-notebook.sh --NotebookApp.token=''
        ports:
            - "${SCIENCEBEAM_JUPYTER_PORT}:8888"
        volumes:
            - .:/opt/sciencebeam-judge
