FROM jupyter/minimal-notebook

ENV PROJECT_HOME=/opt/sciencebeam-judge

WORKDIR ${PROJECT_HOME}

COPY requirements.notebook.txt ${PROJECT_HOME}/
RUN pip install --upgrade pip && \
  pip install -r requirements.notebook.txt

WORKDIR ${PROJECT_HOME}/notebooks
