version: '3'

services:
    sciencebeam-judge-dev:
        environment:
            PYTHONOPTIMIZE: ""
        volumes:
        - ./sciencebeam_judge:/srv/sciencebeam-judge/sciencebeam_judge

    sciencebeam-judge-jupyter:
        volumes:
            - .:/home/jovyan/sciencebeam-judge
            - ~/.config/gcloud:/home/jovyan/.config/gcloud
